spring.application.name=zentrio-testing

spring.datasource.url=jdbc:postgresql://localhost:5432/zentrio_db
spring.datasource.username=postgres
spring.datasource.password=2025


#Config Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zentriokshrd@gmail.com
spring.mail.password=kbud nepd knsj cxac
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.transport.protocol=smtp 
#logging.level.org.thymeleaf=DEBUG

#Minio config
minio.url=http://localhost:9000
minio.access-key=jFUj8joRXEXd2KLLSB2t
minio.secret-key=3RomSlxsdqL9jVCkwyuqYqHgpdXa1yZhnYQH6anB
minio.bucket-name=zentrio-project


# Multipart file size limits
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB



